name: Testing Workflow


# Step 1: Choose the branch or branches you want to run this workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    # Step 0: Grant permissions to access the gradle file
    - name: Grant Execute Permission to gradlew
      run: chmod +x ./gradlew

    # Step 1: Format the kotlin files as best as possible
    - name: Run the spotlessApply command to format our files
      run: ./gradlew spotlessApply

    #Step 2: Attempt to fix standard linting errors
    - name: Run lintFix to attempt to fix linting errors
      run: ./gradlew lintFix

    # Step 3: Check the code with Android linter
    - name: Run Android Linter
      run: ./gradlew lint

    # Step 4: Yun your unit tests
    #- name: Run Unit Tests
    #  run: ./gradlew testStagingDebugUnitTest

    # Step 5: Build the application
    - name: Build the application
      run: ./gradlew build
