name: Deploy Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    # Step 0: Grant permissions to access the gradle file
    - name: Grant Execute Permission to gradlew
      run: chmod +x ./gradlew
