name: Testing Workflow


# Step 1: Choose the branch or branches you want to run this workflow
on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    # Step 0: Grant permissions to access the gradle file
    - name: Grant Execute Permission to gradlew
      run: chmod +x ./gradlew

    # Step 1.2: Check the code with ktlint, you can remove this job if you don't use ktlint
    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck

    # Step 2: Check the code with Android linter
    - name: Run Android Linter
      run: ./gradlew lintStagingDebug

    # Step 4: Yun your unit tests
    #- name: Run Unit Tests
    #  run: ./gradlew testStagingDebugUnitTest

    # Step 4: Assemble debug apk to send to firebase test lab
    #- name: Assemble Debug APK
    #  run: ./gradlew assembleStagingDebug

    # Step 4: Assemble debug test apk to send to firebase test lab
    #- name: Assemble Debug Test APK
    #  run: ./gradlew assembleStagingDebugAndroidTest

    # Step 4: Run instrumented tests on firebase test lab
    #- name: Run tests on Firebase Test Lab
    #  uses: asadmansr/Firebase-Test-Lab-Action@v1.0
    #  with:
    #    arg-spec: '.github/test-lab-config-staging.yml:android-pixel-4'
    #  env:
    #    SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
